version: '2'
services:
    jasees-app:
        image: jasees
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jasees-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jasees
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jasees-mongodb:
        extends:
            file: mongodb.yml
            service: jasees-mongodb
